name: Deploy frontend to Azure Storage

on:
  push:
    branches:
      - main  # o la rama que estés usando
    paths:
      - 'web/**'  # Solo se activa si hay cambios en el directorio frontend
      - .github/workflows/flights-assistant-frontend.yml  # Asegúrate de que el workflow se active con cambios en este archivo

permissions:
      id-token: write
      contents: read      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build site
        run: npm run build
        working-directory: frontend

      - name: Upload to Azure Static Website
        uses: azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination \$web \
              --source frontend/dist \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}