name: Backend Build/Push Docker Image and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # trigger on main branch changes
    paths:
      - 'api/**'  # only trigger on API directory changes
      - .github/workflows/flights-assistant-container-api.yml  # include workflow file changes

permissions:
  id-token: write
  contents: read      

env:
  IMAGE_NAME: flights-api  # container image name without registry prefix
  WEBAPP_NAME: flights-assistant-api  # target Azure Web App name

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('api/requirements.txt', 'api/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-          

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      
      - name: Run tests
        run: |
          cd api
          python -m pytest tests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: grupo4acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: grupo4acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: production
          images: grupo4acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}